### ISSUE TITLE
How did you add your own properties to the cake (machine translation)

### ISSUE THREAD

**Issue by Miros77** [TeamMidnightDust/DeliciousDishes#6]

**Comment by Motschen** [comment]
It's a new block and it uses a blockentity for the particles.

**Comment by Miros77** [comment]
> It's a new block and it uses a blockentity for the particles.

Or you can add your hunger to the cake?
(machine translation)

**Comment by Motschen** [comment]
It just extends the normal cake block, and therefore also the blockstates and hunger values from that.

**Comment by Miros77** [comment]
Please code

2020-10-02 7:16 GMT+03:00, Motschen <notifications@github.com>:

**Comment by Motschen** [comment]
All code for the cake is here: https://github.com/TeamMidnightDust/DeliciousDishes/blob/master/src/main/java/eu/midnightdust/motschen/dishes/block/Cake.java
and here: https://github.com/TeamMidnightDust/DeliciousDishes/blob/master/src/main/java/eu/midnightdust/motschen/dishes/block/blockentity/BirthdayCakeBlockEntity.java
